// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vls.Shopflow.Catalog.Infrastructure;

#nullable disable

namespace Vls.Shopflow.Catalog.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Vls.Shopflow.Catalog.Domain.Entities.AttributeDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AllowCustomValues")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("attribute_definitions", "catalog");
                });

            modelBuilder.Entity("Vls.Shopflow.Catalog.Domain.Entities.AttributeValueDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttributeDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("HexColor")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AttributeDefinitionId");

                    b.ToTable("attribute_value_definitions", "catalog");
                });

            modelBuilder.Entity("Vls.Shopflow.Catalog.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("categories", "catalog");
                });

            modelBuilder.Entity("Vls.Shopflow.Catalog.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<bool>("HasSkus")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("products", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_products_base_price_nonnegative", "(base_regular_price >= 0)\n            AND (base_promo_price IS NULL OR base_promo_price >= 0)");

                            t.HasCheckConstraint("CK_products_base_promo_le_regular", "(base_promo_price IS NULL OR base_promo_price <= base_regular_price)");

                            t.HasCheckConstraint("CK_products_base_promo_window", "(base_promo_start IS NULL OR base_promo_end IS NULL OR base_promo_start <= base_promo_end)");
                        });
                });

            modelBuilder.Entity("Vls.Shopflow.Catalog.Domain.Entities.ProductImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("StoragePath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "IsPrimary");

                    b.HasIndex("ProductId", "SortOrder");

                    b.ToTable("product_images", "catalog");

                    b.HasOne("Vls.Shopflow.Catalog.Domain.Entities.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Vls.Shopflow.Catalog.Domain.Entities.Sku", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId", "Code")
                        .IsUnique();

                    b.ToTable("product_skus", "catalog", t =>
                        {
                            t.HasCheckConstraint("CK_product_skus_price_nonnegative", "(regular_price >= 0)\n            AND (promo_price IS NULL OR promo_price >= 0)");

                            t.HasCheckConstraint("CK_product_skus_promo_le_regular", "(promo_price IS NULL OR promo_price <= regular_price)");

                            t.HasCheckConstraint("CK_product_skus_promo_window", "(promo_start IS NULL OR promo_end IS NULL OR promo_start <= promo_end)");
                        });
                });

            modelBuilder.Entity("Vls.Shopflow.Catalog.Domain.Entities.SkuAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AttributeDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AttributeValueDefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("CustomName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("CustomValue")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("SkuId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AttributeDefinitionId");

                    b.HasIndex("AttributeValueDefinitionId");

                    b.HasIndex("SkuId");

                    b.ToTable("sku_attributes", "catalog");
                });

            modelBuilder.Entity("Vls.Shopflow.Catalog.Domain.Entities.AttributeDefinition", b =>
                {
                    b.HasOne("Vls.Shopflow.Catalog.Domain.Entities.Category", "Category")
                        .WithMany("DefaultAttributes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Vls.Shopflow.Catalog.Domain.Entities.AttributeValueDefinition", b =>
                {
                    b.HasOne("Vls.Shopflow.Catalog.Domain.Entities.AttributeDefinition", "AttributeDefinition")
                        .WithMany("Values")
                        .HasForeignKey("AttributeDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributeDefinition");
                });

            modelBuilder.Entity("Vls.Shopflow.Catalog.Domain.Entities.Product", b =>
                {
                    b.HasOne("Vls.Shopflow.Catalog.Domain.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.OwnsOne("Vls.Shopflow.BuildingBlocks.Domain.ValueObjects.Price", "BasePrice", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("PromoEnd")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("base_promo_end");

                            b1.Property<DateTimeOffset?>("PromoStart")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("base_promo_start");

                            b1.HasKey("ProductId");

                            b1.ToTable("products", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");

                            b1.OwnsOne("Vls.Shopflow.BuildingBlocks.Domain.ValueObjects.Money", "Promotional", b2 =>
                                {
                                    b2.Property<Guid>("PriceProductId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("numeric(12,2)")
                                        .HasColumnName("base_promo_price");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("base_promo_currency");

                                    b2.HasKey("PriceProductId");

                                    b2.ToTable("products", "catalog");

                                    b2.WithOwner()
                                        .HasForeignKey("PriceProductId");
                                });

                            b1.OwnsOne("Vls.Shopflow.BuildingBlocks.Domain.ValueObjects.Money", "Regular", b2 =>
                                {
                                    b2.Property<Guid>("PriceProductId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("numeric(12,2)")
                                        .HasColumnName("base_regular_price");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("base_currency");

                                    b2.HasKey("PriceProductId");

                                    b2.ToTable("products", "catalog");

                                    b2.WithOwner()
                                        .HasForeignKey("PriceProductId");
                                });

                            b1.Navigation("Promotional");

                            b1.Navigation("Regular")
                                .IsRequired();
                        });

                    b.OwnsOne("Vls.Shopflow.Catalog.Domain.ValueObjects.Slug", "Slug", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("slug");

                            b1.HasKey("ProductId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("products", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.Navigation("BasePrice")
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Slug")
                        .IsRequired();
                });

            modelBuilder.Entity("Vls.Shopflow.Catalog.Domain.Entities.Sku", b =>
                {
                    b.HasOne("Vls.Shopflow.Catalog.Domain.Entities.Product", "Product")
                        .WithMany("Skus")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Vls.Shopflow.BuildingBlocks.Domain.ValueObjects.Price", "Price", b1 =>
                        {
                            b1.Property<Guid>("SkuId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("PromoEnd")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("promo_end");

                            b1.Property<DateTimeOffset?>("PromoStart")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("promo_start");

                            b1.HasKey("SkuId");

                            b1.ToTable("product_skus", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("SkuId");

                            b1.OwnsOne("Vls.Shopflow.BuildingBlocks.Domain.ValueObjects.Money", "Promotional", b2 =>
                                {
                                    b2.Property<Guid>("PriceSkuId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("numeric(12,2)")
                                        .HasColumnName("promo_price");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("promo_currency");

                                    b2.HasKey("PriceSkuId");

                                    b2.ToTable("product_skus", "catalog");

                                    b2.WithOwner()
                                        .HasForeignKey("PriceSkuId");
                                });

                            b1.OwnsOne("Vls.Shopflow.BuildingBlocks.Domain.ValueObjects.Money", "Regular", b2 =>
                                {
                                    b2.Property<Guid>("PriceSkuId")
                                        .HasColumnType("uuid");

                                    b2.Property<decimal>("Amount")
                                        .HasColumnType("numeric(12,2)")
                                        .HasColumnName("regular_price");

                                    b2.Property<string>("Currency")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("currency");

                                    b2.HasKey("PriceSkuId");

                                    b2.ToTable("product_skus", "catalog");

                                    b2.WithOwner()
                                        .HasForeignKey("PriceSkuId");
                                });

                            b1.Navigation("Promotional");

                            b1.Navigation("Regular")
                                .IsRequired();
                        });

                    b.Navigation("Price")
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Vls.Shopflow.Catalog.Domain.Entities.SkuAttribute", b =>
                {
                    b.HasOne("Vls.Shopflow.Catalog.Domain.Entities.AttributeDefinition", "AttributeDefinition")
                        .WithMany()
                        .HasForeignKey("AttributeDefinitionId");

                    b.HasOne("Vls.Shopflow.Catalog.Domain.Entities.AttributeValueDefinition", "AttributeValueDefinition")
                        .WithMany()
                        .HasForeignKey("AttributeValueDefinitionId");

                    b.HasOne("Vls.Shopflow.Catalog.Domain.Entities.Sku", "Sku")
                        .WithMany("Attributes")
                        .HasForeignKey("SkuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributeDefinition");

                    b.Navigation("AttributeValueDefinition");

                    b.Navigation("Sku");
                });

            modelBuilder.Entity("Vls.Shopflow.Catalog.Domain.Entities.AttributeDefinition", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("Vls.Shopflow.Catalog.Domain.Entities.Category", b =>
                {
                    b.Navigation("DefaultAttributes");
                });

            modelBuilder.Entity("Vls.Shopflow.Catalog.Domain.Entities.Product", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Skus");
                });

            modelBuilder.Entity("Vls.Shopflow.Catalog.Domain.Entities.ProductImage", b =>
                {
                    b.Navigation("Product");
                });

            modelBuilder.Entity("Vls.Shopflow.Catalog.Domain.Entities.Sku", b =>
                {
                    b.Navigation("Attributes");
                });
#pragma warning restore 612, 618
        }
    }
}
